### ISSUE TITLE
How to get desktop notifications to work

### ISSUE THREAD

**Issue by jezzdk** [nativefier/nativefier#1292]
**Homework**

- [ x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [x ] I searched existing issues, open & closed. Yes, my question is new.
- [x ] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Your question**

I'm trying to get desktop notifications to show up on my Macbook. 
I've created an app for Google Calendar.
I've enabled desktop notifications in Google Calendar, no errors.
A sound is playing but no notification pops up.
The app is not listed in Notifications in Mac System Settings.

**Steps to reproduce**

I'm using this command: `nativefier --name 'Google Calendar' 'calendar.google.com'`

**Context**

 - Nativefier: 45.0.4
 - Node.js: 12.21.0
 - Npm: 6.14.11
 - OS: Mac OS 11.5.2

**Comment by jezzdk** [comment]
I just updated to the latest version, which should fix something with notifications, but still nothing pops up. I've deleted the app and rebuilt it. Also tried with the `--clear-cache` flag.

I'm using a Macbook Pro M1 by the way. Not sure if that changes anything. I've built the app for arm64.

**Comment by mtharpe** [comment]
I am also seeing the same issue in OSX 12.0.1. I have updated to the latest version, and verified that there is no cache causing issues.

**Comment by ronjouch** [comment]
Should be fixed thanks to #1308, please test Nativefier 45.0.6, on npm in a few minutes/hours.

**Comment by mtharpe** [comment]
I tested with 45.0.6 and still get no pop up notifications. I do get sound, but no visual notifications. I also cleared the cache, reinstalled NPM, and verified clean install of Nativefier and new creation of the App.

**Comment by mtharpe** [comment]
Also, another thing to note is that the app does not show up in the OSX System Preferences/Notifications area.

**Comment by ronjouch** [comment]
> I tested with 45.0.6 and still get no pop up notifications. I do get sound, but no visual notifications. I also cleared the cache, reinstalled NPM, and verified clean install of Nativefier and new creation of the App.
>
> Also, another thing to note is that the app does not show up in the OSX System Preferences/Notifications area.

Thanks @mtharpe ! @exander77 @jezzdk, do you confirm?

**Comment by jezzdk** [comment]
@ronjouch I can confirm that the problem persists with the update.

**Comment by mtharpe** [comment]
Ok, so I have a Linux machine that I have been using a lot and was able to get it working on there. So I took what I did on Linux and got it working on my Mac with these settings:

**Step 1:**
`
sudo npm install -g electron@15.2.0
`
`
sudo npm install -g nativefier@45.0.4
`
`
sudo npm install -g node-gyp@8.2.0
`
`
sudo npm install -g node.js@0.0.1-security
`
`
sudo npm install -g nopt@5.0.0
`
`
sudo npm install -g npm@8.1.3
`
`
sudo npm install -g semver@7.3.5
`

**Step 2:** 
Re-Create my Google Calendar app:
`
nativefier "https://calendar.google.com/" --maximize --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0" --name "Google Calendar" --internal-urls "(.*?calendar.google.com.*?|.*?accounts.google.com.*?|.*google.com.*|.*okta.com.*)" -i ~/Pictures/icons/Google_Calendar.icns
`
**Note:** The user-agent matters here, and I was able to find a working agent via the Arch packages!!!!!

**Comment by jezzdk** [comment]
@mtharpe Interesting. It indeed seems to work if you set the user agent. I didn't perform Step 1 so it should work with older version it seems (I have Electron 13.6.2, Node 12.21 and npm 6.14.11).

This is the command I used to build: `nativefier "https://calendar.google.com/" --maximize --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0" --name "Google Calendar"`

**Comment by ronjouch** [comment]
@exander77 do you confirm that notifications are still broken in 45.0.6? Should we revert #1308 ?

**Comment by elfassy** [comment]
@mtharpe @jezzdk did you have to do anything else? I've tried with the user-agent you shared, but no luck
```
➜  nativefier npm list | grep electron
└── electron@16.0.4
➜  nativefier npm -v
8.1.4
➜  nativefier nativefier --version
45.0.8
```

**Comment by jezzdk** [comment]
@elfassy No thats all I did. But it seems to be very random. I only get a desktop notification every once in a while. I've decided to save the hassle and flesh out the dollars for Unite 4 instead.

**Comment by schloram** [comment]
Since I changed the user-agent to Firefox (`--user-agent 'firefox'`) notifications do work. Not the best way to solve this, but it works. 🤷
