### ISSUE TITLE
Gmail, Evernote, ... login broken because navigator.cookieEnabled is set to false after navigation [Electron 7 regression] 

### ISSUE THREAD

**Issue by allo-** [nativefier/nativefier#902]
``navigator.cookieEnabled`` is set to false and triggers "Your browser does not support cookies" warnings.

### Details

When a website checks for ``navigator.cookieEnabled``, nativefier returns ``false``. I checked this in the console and it is ``false`` and not even ``undefined``. 

Nativefier Version: 7.7.0
Node Version: 10.17.0
OS: Linux

**Comment by ronjouch** [comment]
@allo- thanks for the feedback. On which website? Please share the full command-line example to reproduce the issue.

**Comment by allo-** [comment]
A private [rainloop](https://www.rainloop.net/try-now/) installation. You can test with their online demo.

Command Line: 

    nativefier --single-instance --name "RainloopTest" https://mail.rainloop.net/

When you login to the demo, you get redirected to a "No cookies enabled" page.

I patched the private rainloop and removed the check and the nativefied site works fine and remembers cookies even across closing and starting the app again, but the detection using `navigator.cookiesEnabled` fails.

**Comment by ronjouch** [comment]
> I patched the private rainloop and removed the check and the nativefied site works fine and remembers cookies even across closing and starting the app again, but the detection using `navigator.cookiesEnabled` fails.

Thanks. `navigator.cookiesEnabled` contains `true` in an Electron 8 app built with the rework I'm finishing at https://github.com/jiahaog/nativefier/pull/898 . So, you should be okay once the rework is merged, and you have a workaround, so closing.

**Comment by ronjouch** [comment]
Re-opening. `navigator.cookieEnabled` (note to self: no 's', cookieEnabled, not cookiesEnabled) is initially set to `true` on app load, but becomes `undefined` after navigation to any page, breaking logins.

**Comment by nstielau** [comment]
I'm able to reproduce this as well.  Thanks for the workaround!

**Comment by nartcan** [comment]
I had the same issue trying with music.youtube.com

**Comment by nstielau** [comment]
Yeah, unfortunately it is pretty widespread.

**Comment by ronjouch** [comment]
:wave: everybody here. I just released [Nativefier v9.0.0](https://github.com/jiahaog/nativefier/releases/tag/v9.0.0) which defaults to Electron 9.0.4, and I read in https://github.com/electron/electron/issues/21256#issuecomment-630306506 that *"Electron 9 is no longer affected by this issue"* (which since disappeared from the thread). So, not sure if this is fixed or not, tests welcome.

**Comment by fidelix** [comment]
This is still a problem. Just tested with a fresh nativefier.

**Comment by armenr** [comment]
Still a problem I think!

**Comment by marcboscher** [comment]
@ronjouch your workaround [here](https://github.com/jiahaog/nativefier/issues/902#issue-564968685) doesn't seem to work sadly.

`nativefier "gmail.com" -e 6.1.9`

![image](https://user-images.githubusercontent.com/1174558/103493898-fe1a4380-4e01-11eb-9e79-1a132785cc38.png)

any ideas?

**Comment by MynockSpit** [comment]
@marcboscher  Looks like this issue is solved by setting the user agent on build (described here: https://github.com/nativefier/nativefier/issues/831).

**Comment by TheCleric** [comment]
Is anyone else still having issues around `navigator.cookieEnabled` being false? I can not reproduce this on the latest version of Nativefier.

**Comment by TheCleric** [comment]
Closing as I have not heard a response back. We can reopen if anyone is still experiencing this.
